name: General CI

on:
  push:
    branches: [ "develop", "main" ]
  pull_request:
    branches: [ "develop", "main" ]

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20' # Ajustar a tu versión
          
      - name: Placeholder Step
        run: echo "Aquí irán los comandos de instalación (ej. npm install) y de test (npm run test)"
